Post.create({title: "My Post1", body: "Lorem ipsum, oisndfasd;fpoin sdofin a;soinewsdfnoi s.s. df"})
Post.create({title: "My Post2", body: "Lorem ipsum, oisndfasd;fpoin sdofin a;soinewsdfnoi s.s. df"})
Post.create({title: "My Post3", body: "Lorem ipsum, oisndfasd;fpoin sdofin a;soinewsdfnoi s.s. df"})
Post.create({title: "My Post4", body: "Lorem ipsum, oisndfasd;fpoin sdofin a;soinewsdfnoi s.s. df"})
Post.create({title: "My Post5", body: "Lorem ipsum, oisndfasd;fpoin sdofin a;soinewsdfnoi s.s. df"})